### ISSUE TITLE
Create a Jekyll compatible design implementation of the FOSSASIA style and add it to

### ISSUE THREAD

**Issue by mariobehling** [fossasia/knitting.fossasia.org#11]
We often need to create a simple mini-site. We want to be able to create a md file with markup and add a Jekyll style. The knitting site does not use the FOSSASIA style yet. 

Please create a Jekyll implementation of the FOSSASIA design and add it to http://knitting.fossasia.org/

Include the top bar and side bar and make different areas into sections.

**Comment by Subhash-Saurabh** [comment]
Is it really important to make  "different areas into section" ? Can't we keep the site as https://labs.fossasia.org/ideas.html where we keep top_bar and footer but apart from that we keep all the content together.

I am asking this because jekyll doesn't provide good methods for splitting the contents (after lots of googling) . If I am missing something please point out .

**Comment by mariobehling** [comment]
In the meantime we have developed Yaydoc as a project and work on this subject should probably continue there: https://github.com/fossasia/yaydoc

Therefore closing this.
