### ISSUE TITLE
add talk to how to create repository

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/knitting.fossasia.org#7]
add this talk to the site: https://www.youtube.com/watch?v=Ksiim1Crvvc

**Comment by mariobehling** [comment]
Are these things maybe too small to create issues for them?

**Comment by niccokunzmann** [comment]
@mariobehling 

Algorithm:

```
if I have time to add the small thing, I add the code.
else if I have a good idea but no time, I add an issue:
    This is the case if I must leave the house or I am focused on implementing,
    I add small issues to not loose track and stay focused.
```

**Comment by mariobehling** [comment]
Let's focus on knitting projects on this site and rather add other interesting stuff to the blog or simply link to it. I think we should not build a site "how to use github etc" and just focus on knitting. Also as this issue is so old, it shows that we don't have resources to focus on other things. Closing it therefore.
